### ISSUE TITLE
Question about elastic_constant.

### ISSUE THREAD

**Issue by plasmon1977** [hackingmaterials/amset#143]
Dear Developers,

According to the manual, the value of elastic_constant is obtained by averaging the direction-dependent elastic constant. Do you calculate this parameter by averaging the TOTAL_ELASTIC_MODULI generating by VASP when setting "IBRION=6"? If this value is calculated by averaging, how to obtain the anisotropic mobility?Thank you!

Hao Zhang

**Comment by utf** [comment]
Hi Hao,

There are a few ways of calculating the elastic properties. The inbuilt functionality in VASP should be fine. We have used the stress-strain fitting approach detailed in [10.1038/sdata.2015.9](https://doi.org/10.1038/sdata.2015.9), which we find to be a bit more robust. We then take the spherical average of the tensor as you mentioned. 

You still get anisotropic properties due to:
- Any anisotropy in the band structure, which comes through the group velocities.
- Any anisotropy in the scattering rates, which can arise from the matrix elements (i.e., anisotropy in the wave function overlap) or the phase space available for scattering (i.e., if a band is less disperse in one direction there will be more states to scatter to).

The amset_data file contains the full mobility tensor in it, containing any anisotropy.

This should be sufficient to capture most of the anisotropy in your material. However, if your elastic constant is extremely anisotropic, you can always run AMSET multiple times using the different eigenvalues of your elastic constant. You can then take the component of mobility in the direction that corresponds to the eigenvalue of the elastic constant you've chosen.

Best,
Alex

**Comment by meihaod** [comment]
Dear Developers,
What do you mean by  the spherical average of the tensor?
Is it the avearge of all components of the tensor or the average of  (C11+C22+C33) ?
Thank you !
Haodong Mei

**Comment by utf** [comment]
Hi @meihaod, for elastic constants we are only interested in the longitudinal elastic constants, so you can just take the average of C11+C22+C33.

For dielectric constants, you should take the eigenvalues of the tensor and then average those.

**Comment by utf** [comment]
Just a note that in the next few weeks I will implement a method to take into account the full anisotropy of the elastic/dielectric constants automatically.

**Comment by utf** [comment]
Hi @plasmon1977 and @meihaod 

AMSET now supports full elastic, dielectric, and piezoelectric tensors. You can see an example input file here: https://github.com/hackingmaterials/amset/blob/master/examples/Si/settings.yaml
